<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Init</name>
  <uuid>9207be86-dab3-4b2f-bba6-0e5ae8938bed</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to a new counter where
		the FC is 0 , 
		the MC is 0 ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
