<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>MarketCounter</name>
  <uuid>d613b54f-3f00-4cb8-a475-b6d0b310ef59</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[definitions
  set Market to {"stocks crash","panic selling","stocks have taken a beating","share price manipulation","litany of allegations","Massive selling"};
  -- loop on list 1
set item1 to a string in Market;
-- check item in list 2
if there is at least one string in Input
	where this string is item1 ,
then
   set the MC of decision to the MC of decision + 1;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
