<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>80096393-c273-4acd-bca2-eb28cefad8f9</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to "No Match" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
